/* ACTION TYPES */

export const GET_CRYPTOCCY_DATA = 'GET_CRYPTOCCY_DATA'
export const GET_CRYPTOCCY_DATA_SUCCESS = 'GET_CRYPTOCCY_DATA_SUCCESS'
export const GET_CRYPTOCCY_DATA_ERROR = 'GET_CRYPTOCCY_DATA_ERROR'
